-- =====================================================================================
-- V1: Platform baseline
--
-- Schema conventions applied by every later migration:
--   * Primary keys: UUID (time-ordered, generated by the application).
--   * Money: NUMERIC(19,4) + CHAR(3) ISO-4217 currency column; CHECK (amount >= 0) where
--     the value can never be negative.
--   * Timestamps: TIMESTAMPTZ, always written in UTC.
--   * Mutable aggregates carry "version BIGINT" for optimistic locking.
--   * Immutable records (ledgers, audit logs, earnings) attach forbid_mutation() below.
-- =====================================================================================

-- Rejects UPDATE and DELETE on append-only tables, so financial history cannot be altered even
-- by a buggy code path or a manual SQL session. Corrections must be new compensating entries.
CREATE OR REPLACE FUNCTION forbid_mutation() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'Table % is append-only: % is not permitted', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

COMMENT ON FUNCTION forbid_mutation() IS
    'Attach with: CREATE TRIGGER <t>_immutable BEFORE UPDATE OR DELETE ON <t> FOR EACH ROW EXECUTE FUNCTION forbid_mutation();';
