package com.sealease.backend.audit;

/** Every auditable action. Stored by name, so constants must never be renamed once released. */
public enum AuditAction {

	USER_REGISTERED,
	LOGIN,
	LOGIN_FAILED,
	ACCOUNT_LOCKED,
	LOGOUT,
	LOGOUT_ALL,
	TOKEN_REFRESH_REUSE_DETECTED,
	PASSWORD_CHANGE,

	ROLE_CREATED,
	ROLE_UPDATED,
	ROLE_DELETED,
	USER_ROLES_CHANGED,

	PROFILE_UPDATED,
	TAX_INFO_UPDATED,
	USER_SUSPENDED,
	USER_REACTIVATED,
	INVESTOR_CLASSIFIED,

	KYC_SUBMITTED,
	KYC_APPROVED,
	KYC_REJECTED,
	KYC_DOCUMENT_VIEWED,

	BANK_ACCOUNT_ADDED,
	BANK_ACCOUNT_REMOVED,
	BANK_ACCOUNT_PRIMARY_CHANGED,
	BANK_ACCOUNT_VERIFIED,
	BANK_ACCOUNT_REJECTED,

	CONTAINER_CREATED,
	CONTAINER_UPDATED,
	CONTAINER_STATUS_CHANGED,
	CONTAINER_DOCUMENT_ADDED,
	CONTAINER_DOCUMENT_VISIBILITY_CHANGED,

	PRODUCT_CREATED,
	PRODUCT_UPDATED,
	PRODUCT_PUBLISHED,
	PRODUCT_CANCELLED,
	PRODUCT_LEASE_ACTIVATED,
	PRODUCT_MATURED,

	ORDER_PLACED,
	ORDER_CANCELLED,
	ORDER_EXPIRED,
	ORDER_CONFIRMED,

	PAYMENT_STARTED,
	PAYMENT_SUCCEEDED,
	PAYMENT_FAILED,
	PAYMENT_REFUND_REQUIRED,
	PAYMENT_REFUNDED,

	INVOICE_ISSUED,

	RENTAL_RECORDED,
	RENTAL_DISTRIBUTED,
	RENTAL_REJECTED,
	LEDGER_ADJUSTMENT_POSTED,

	REFERRAL_LINKED,
	REFERRAL_RATES_SCHEDULED,
	REFERRAL_RATES_CANCELLED,
	REFERRAL_COMMISSIONS_PAID,

	WITHDRAWAL_REQUESTED,
	WITHDRAWAL_CANCELLED,
	WITHDRAWAL_APPROVED,
	WITHDRAWAL_REJECTED,
	WITHDRAWAL_PAID,
	WITHDRAWAL_FAILED,
	WITHDRAWAL_BATCH_CREATED,
	WITHDRAWAL_BATCH_CANCELLED,
	WITHDRAWAL_BATCH_EXPORTED,
	WITHDRAWAL_BATCH_SENT,
	WITHDRAWAL_BATCH_CLOSED,

	LEAD_CREATED,
	LEAD_ASSIGNED,
	LEAD_WON,

	TICKET_OPENED,
	TICKET_ASSIGNED,
	TICKET_STATUS_CHANGED,
	TICKET_PRIORITY_CHANGED,
	TICKET_ATTACHMENT_VIEWED

}
