/** Permission codes the UI reacts to. Mirrors backend PermissionCode; display logic only. */
export const Permission = {
  INVESTOR_PORTAL: "INVESTOR_PORTAL",
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_MANAGE: "ROLE_MANAGE",
  USER_ROLE_ASSIGN: "USER_ROLE_ASSIGN",
  USER_VIEW: "USER_VIEW",
  USER_SUSPEND: "USER_SUSPEND",
  KYC_REVIEW: "KYC_REVIEW",
  INVESTOR_CLASSIFY: "INVESTOR_CLASSIFY",
  BANK_ACCOUNT_VERIFY: "BANK_ACCOUNT_VERIFY",
  FINANCE_VIEW: "FINANCE_VIEW",
  FINANCE_ADJUST: "FINANCE_ADJUST",
  PAYMENT_CONFIRM: "PAYMENT_CONFIRM",
  RENTAL_RECORD: "RENTAL_RECORD",
  RENTAL_APPROVE: "RENTAL_APPROVE",
  REFERRAL_CONFIG_MANAGE: "REFERRAL_CONFIG_MANAGE",
  WITHDRAWAL_VIEW: "WITHDRAWAL_VIEW",
  WITHDRAWAL_APPROVE: "WITHDRAWAL_APPROVE",
  WITHDRAWAL_REJECT: "WITHDRAWAL_REJECT",
  WITHDRAWAL_PROCESS: "WITHDRAWAL_PROCESS",
  LEAD_VIEW: "LEAD_VIEW",
  LEAD_CREATE: "LEAD_CREATE",
  LEAD_ASSIGN: "LEAD_ASSIGN",
  LEAD_UPDATE: "LEAD_UPDATE",
  SUPPORT_TICKET_VIEW: "SUPPORT_TICKET_VIEW",
  SUPPORT_TICKET_MANAGE: "SUPPORT_TICKET_MANAGE",
  REPORT_VIEW: "REPORT_VIEW",
  REPORT_GENERATE: "REPORT_GENERATE",
  ORDER_VIEW: "ORDER_VIEW",
  INVESTMENT_VIEW: "INVESTMENT_VIEW",
  INVESTMENT_CREATE: "INVESTMENT_CREATE",
  INVESTMENT_UPDATE: "INVESTMENT_UPDATE",
  INVESTMENT_APPROVE: "INVESTMENT_APPROVE",
} as const;

/** Any permission beyond the investor portal grants access to the staff console. */
export function hasStaffAccess(permissions: readonly string[]): boolean {
  return permissions.some((p) => p !== Permission.INVESTOR_PORTAL);
}

export function hasPermission(permissions: readonly string[], permission: string): boolean {
  return permissions.includes(permission);
}
